version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/vite/admin"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/vite/count"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/vite/public"
    schedule:
      interval: "weekly"
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
